options:
  lineNumbers: true
  imagePath: /blogimgs
  askImageFilename: true
  spellcheck: false
  overwriteImages: false
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: false
