# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小胡子哥的个人网站
title_en: Barret Lee's personal website
subtitle: For Future, For Freedom.
description: 想法，随笔，思考，感叹，瞬间，笔记...
author: 小胡子哥 # Barret Lee
language: zh-cn
timezone: Asia/Shanghai

imgCDN: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.barretlee.com
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: src
public_dir: build
tag_dir: blog/tags
archive_dir: blog/archives
category_dir: blog/categories
code_dir: blog/downloads/code
i18n_dir: blog/:lang
skip_render: tmp

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: true

# Category & Tag
default_category: other
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: p

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hexo-theme-moustache

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: git@git.coding.net:barretlee/myblog.git
  branch: coding-pages
  message: build at local, send to coding-pages {{ now("YYYY-MM-DD HH:mm:ss") }}
- type: git
  repo: git@github.com:barretlee/blog.git
  branch: gh-pages
  message: build at local, send to gh-pages {{ now("YYYY-MM-DD HH:mm:ss") }}
#- type: git
  #repo: https://gitcafe.com/barretlee/blog.git
  #branch: gitcafe-pages
  #message: build at local, send to gitcafe-pages {{ now("YYYY-MM-DD HH:mm:ss") }}



# - type: heroku
#   repo:
# - type: rsync
#   host: <host>
#   user: <user>
#   root: <root>
#   port: [port]
#   delete: false
#   verbose: true
#   ignore_errors: false
# - type: ftpsync
#   host: <host>
#   user: <user>
#   pass: <password>
#   remote: [remote]
#   port: [port]
#   ignore: [ignore]
#   connections: [connections]
#   verbose: [true|false]

# hey Admin
# admin:
#   name: barretlee
#   password: u201012877
#   secret: barret lee's secret
#   expire: 60*1
#   # cors: http://localhost:3000

# hexo-admin authentification
admin:
  username: barretlee
  password_hash: $2a$10$FbsgxcpJq2waz3ztBIvQKeYMjyf7HugaMrNZHTaByD6FtZd8FE9EO
  secret: barret lee's secret
  deployCommand: cd ..; make d; make b P=1;

metadata:
  description: 小胡子哥的个人网站
  warning: true

search:
  path: search.xml
  field: post

imgurl: /blogimg/

# for hexo all minifier
all_minifier: true
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false
html_minifier:
  enable: true
  ignore_error: true
  silent: false
  exclude: 
    - '/ST/'
css_minifier:
  enable: true
  silent: false
  exclude: 
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  silent: false
  output:
  compress:
  exclude: 
    - '*.min.js'
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false

# for img lazyload
lazyload:
  enable: true 
  onlypost: true
  loadingImg: //img.alicdn.com/tfs/TB1oyqGa_tYBeNjy1XdXXXXyVXa-300-300.png


# webpack_config: 'themes/hexo-theme-moustache/webpack.config.js'


# offline config passed to sw-precache. 
# service_worker:
#   maximumFileSizeToCacheInBytes: 5242880
#   staticFileGlobs:
#     - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
#   stripPrefix: public
#   verbose: true
#   runtimeCaching:
#     - urlPattern: /*
#       handler: cacheFirst
#       options:
#         origin: changyan.sohu.com
#     - urlPattern: /*
#       handler: cacheFirst
#       options:
#         origin: changyan.itc.cn